services:
  _defaults:
    autowire: true
    autoconfigure: true

  ICS\MediaBundle\Controller\:
    resource: "../src/Controller"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Service\:
    resource: "../src/Service"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Command\:
    resource: "../src/Command"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Twig\:
    resource: "../src/Twig"
    public: false
    tags: ['twig.extension']
  ICS\MediaBundle\Form\:
    resource: "../src/Form"
    public: false